"""Designer ui file compiled into python code for adding a schedule"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(596, 324)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(230, 230, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(250, 20, 111, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(130, 180, 101, 31))
        self.label_2.setObjectName("label_2")
        self.day_week = QtWidgets.QComboBox(Dialog)
        self.day_week.setGeometry(QtCore.QRect(330, 180, 131, 26))
        self.day_week.setObjectName("day_week")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(130, 70, 141, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(130, 130, 101, 31))
        self.label_4.setObjectName("label_4")
        self.name_schedule = QtWidgets.QLineEdit(Dialog)
        self.name_schedule.setGeometry(QtCore.QRect(330, 70, 131, 26))
        self.name_schedule.setAlignment(QtCore.Qt.AlignCenter)
        self.name_schedule.setObjectName("name_schedule")
        self.start_hour = QtWidgets.QLineEdit(Dialog)
        self.start_hour.setGeometry(QtCore.QRect(300, 130, 31, 26))
        self.start_hour.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.start_hour.setAlignment(QtCore.Qt.AlignCenter)
        self.start_hour.setObjectName("start_hour")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(340, 130, 20, 21))
        self.label_5.setObjectName("label_5")
        self.start_min = QtWidgets.QLineEdit(Dialog)
        self.start_min.setGeometry(QtCore.QRect(350, 130, 31, 26))
        self.start_min.setAlignment(QtCore.Qt.AlignCenter)
        self.start_min.setObjectName("start_min")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(390, 130, 20, 21))
        self.label_6.setObjectName("label_6")
        self.end_hour = QtWidgets.QLineEdit(Dialog)
        self.end_hour.setGeometry(QtCore.QRect(410, 130, 31, 26))
        self.end_hour.setAlignment(QtCore.Qt.AlignCenter)
        self.end_hour.setObjectName("end_hour")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(450, 130, 20, 21))
        self.label_7.setObjectName("label_7")
        self.end_min = QtWidgets.QLineEdit(Dialog)
        self.end_min.setGeometry(QtCore.QRect(460, 130, 31, 26))
        self.end_min.setAlignment(QtCore.Qt.AlignCenter)
        self.end_min.setObjectName("end_min")
        self.error_dialog = QtWidgets.QLabel(Dialog)
        self.error_dialog.setGeometry(QtCore.QRect(20, 270, 561, 31))
        self.error_dialog.setText("")
        self.error_dialog.setAlignment(QtCore.Qt.AlignCenter)
        self.error_dialog.setObjectName("error_dialog")

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Add Schedule"))
        self.label_2.setText(_translate("Dialog", "Day of Week"))
        self.label_3.setText(_translate("Dialog", "Name of Schedule:"))
        self.label_4.setText(_translate("Dialog", "Timing:"))
        self.label_5.setText(_translate("Dialog", ":"))
        self.label_6.setText(_translate("Dialog", "to"))
        self.label_7.setText(_translate("Dialog", ":"))
