from PyQt5 import QtCore, QtGui, QtWidgets

from UI.Layouts.base_designer import add_widget_to_layout


class Ui_MainWindow(object):

    def __init__(self):
        self.create_hz_layout = QtWidgets.QHBoxLayout()
        self.convert_hz_layout = QtWidgets.QHBoxLayout()
        self.target_hz_layout = QtWidgets.QHBoxLayout()
        self.current_hz_layout = QtWidgets.QHBoxLayout()
        self.load_hz_layout = QtWidgets.QHBoxLayout()
        self.central_widget = QtWidgets.QWidget()
        self.vertical_layout = QtWidgets.QVBoxLayout()
        self.title_hz_layout = QtWidgets.QHBoxLayout()
        self.title = QtWidgets.QLabel(self.central_widget)
        self.load_label = QtWidgets.QLabel(self.central_widget)
        self.current_tz_drop_down = QtWidgets.QComboBox(self.central_widget)
        self.current_label = QtWidgets.QLabel(self.central_widget)
        self.target_tz_drop_down = QtWidgets.QComboBox(self.central_widget)
        self.target_label = QtWidgets.QLabel(self.central_widget)
        self.convert = QtWidgets.QPushButton(self.central_widget)
        self.create_label = QtWidgets.QLabel(self.central_widget)
        self.create = QtWidgets.QPushButton(self.central_widget)

    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.central_widget.setParent(MainWindow)
        self.central_widget.setObjectName("centralwidget")
        self.vertical_layout.setObjectName("verticalLayout")
        self.title_hz_layout.setObjectName("horizontalLayout_4")

        spacerItem = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.title_hz_layout.addItem(spacerItem)
        font = QtGui.QFont()
        font.setFamily("FreeMono")
        font.setPointSize(20)
        self.title.setFont(font)
        add_widget_to_layout(self.title, self.title_hz_layout, 'title')
        spacerItem1 = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.title_hz_layout.addItem(spacerItem1)
        self.vertical_layout.addLayout(self.title_hz_layout)

        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout.addItem(spacerItem3)
        self.load_hz_layout.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(318, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.load_hz_layout.addItem(spacerItem4)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.load_label.setFont(font)
        add_widget_to_layout(self.load_label, self.load_hz_layout, 'load')
        spacerItem5 = QtWidgets.QSpacerItem(308, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.load_hz_layout.addItem(spacerItem5)
        self.vertical_layout.addLayout(self.load_hz_layout)

        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout.addItem(spacerItem6)
        self.current_hz_layout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.current_hz_layout.addItem(spacerItem7)
        self.current_label.setMinimumSize(QtCore.QSize(147, 0))
        self.current_label.setAlignment(QtCore.Qt.AlignCenter)
        add_widget_to_layout(self.current_label, self.current_hz_layout, 'current')
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_tz_drop_down.sizePolicy().hasHeightForWidth())
        self.current_tz_drop_down.setSizePolicy(sizePolicy)
        self.current_tz_drop_down.setMinimumSize(QtCore.QSize(241, 26))
        add_widget_to_layout(self.current_tz_drop_down, self.current_hz_layout, 'drop_current')

        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.current_hz_layout.addItem(spacerItem8)
        self.vertical_layout.addLayout(self.current_hz_layout)
        spacerItem9 = QtWidgets.QSpacerItem(18, 73, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout.addItem(spacerItem9)
        self.target_hz_layout.setObjectName("horizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.target_hz_layout.addItem(spacerItem10)
        self.target_label.setMinimumSize(QtCore.QSize(139, 0))
        self.target_label.setAlignment(QtCore.Qt.AlignCenter)
        add_widget_to_layout(self.target_label, self.target_hz_layout, 'target')
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.target_tz_drop_down.sizePolicy().hasHeightForWidth())
        self.target_tz_drop_down.setSizePolicy(sizePolicy)
        self.target_tz_drop_down.setMinimumSize(QtCore.QSize(241, 0))
        add_widget_to_layout(self.target_tz_drop_down, self.target_hz_layout, 'target_drop')

        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.target_hz_layout.addItem(spacerItem11)
        self.vertical_layout.addLayout(self.target_hz_layout)
        spacerItem12 = QtWidgets.QSpacerItem(18, 73, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout.addItem(spacerItem12)
        self.convert_hz_layout.setObjectName("horizontalLayout_6")
        spacerItem13 = QtWidgets.QSpacerItem(358, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.convert_hz_layout.addItem(spacerItem13)
        add_widget_to_layout(self.convert, self.convert_hz_layout, 'convert')
        spacerItem14 = QtWidgets.QSpacerItem(378, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.convert_hz_layout.addItem(spacerItem14)
        self.vertical_layout.addLayout(self.convert_hz_layout)

        spacerItem15 = QtWidgets.QSpacerItem(18, 73, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout.addItem(spacerItem15)
        self.create_hz_layout.setObjectName("horizontalLayout_3")
        self.create_label.setAlignment(QtCore.Qt.AlignCenter)
        add_widget_to_layout(self.create_label, self.create_hz_layout, 'create_label')
        add_widget_to_layout(self.create, self.create_hz_layout, 'create_button')
        self.vertical_layout.addLayout(self.create_hz_layout)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout.addItem(spacerItem16)
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslate_ui(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.central_widget.setLayout(self.vertical_layout)

    def retranslate_ui(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Cross Time-Zone Timetable"))
        self.load_label.setText(_translate("MainWindow", "Load Timetable"))
        self.current_label.setText(_translate("MainWindow", "                    Current Time Zone:                    "))
        self.target_label.setText(_translate("MainWindow", "                    Target Time Zone:                    "))
        self.convert.setText(_translate("MainWindow", "Convert"))
        self.create_label.setText(_translate("MainWindow", "Create Timetable:"))
        self.create.setText(_translate("MainWindow", "Create"))
